name: LonelyBadges
main: com.ne0nx3r0.badges.LonelyBadgesPlugin
version: '0.3a'
database: false
description: Badging system for players
softdepend: [Vault]
commands:
   badges:
       description: Badges command
       aliases: bg