name: LonelyBadges
main: com.ne0nx3r0.badges.LonelyBadgesPlugin
version: '0.1a'
database: false
description: Badging system for players
commands:
   badges:
       description: Badges command
       aliases: bg